---
- hosts: server1
  become: yes
  roles:
    - role: docker
  vars:
    apps:
      - uptime-kuma

- hosts: server2
  become: yes
  roles:
    - role: docker
  vars:
    apps:
      - mariadb
      - yourls
      - linkstack
      - nextcloud
      - phpmyadmin