---
- name: Install Nginx and deploy website
  hosts: server1
  become: yes
  vars:
    github_token: "token"
    repo_url: "https://arigints:{{ github_token }}@github.com/arigints/personal-website.git"
    web_root: "/var/www/html"

  tasks:
    - name: Update the package index
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled at boot
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Remove default Nginx index page
      file:
        path: "{{ web_root }}/index.nginx-debian.html"
        state: absent

    - name: Clone website repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ web_root }}"
        version: master  # Gunakan branch yang sesuai

    - name: Set proper permissions for web files
      file:
        path: "{{ web_root }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Configure Nginx for the website
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;

              root {{ web_root }};
              index index.html index.htm;

              server_name _;

              location / {
                  try_files $uri $uri/ =404;
              }
          }

    - name: Test Nginx configuration
      command: nginx -t

    - name: Reload Nginx to apply new configuration
      service:
        name: nginx
        state: reloaded