---
- name: Install Wireguard service
  hosts: biznet
  become: true

  tasks:
    - name: Enable EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Import ELRepo GPG key
      rpm_key:
        state: present
        key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

    - name: Install ELRepo
      yum:
        name: "https://www.elrepo.org/elrepo-release-9.el9.elrepo.noarch.rpm"
        state: present

    - name: Required packages are installed and up to date
      yum:
        update_cache: yes
        name:
          - wireguard-tools
        state: latest

    - name: Write the wireguard client config file
      template:
        src: ./wgconf/wg0.conf
        dest: /etc/wireguard/wg0.conf

    - name: Wireguard is started and enabled
      service:
        name: systemd-resolved
        state: started
        enabled: true

    - name: Wireguard is started and enabled
      service:
        name: wg-quick@wg0
        state: started
        enabled: true

    - name: Ping VPN gateway to check connectivity
      shell: ping -c 2 10.0.0.1
      register: ping_result
      ignore_errors: yes

    - name: Display ping results
      debug:
        msg: "{{ item }}"
      loop: "{{ ping_result.stdout_lines }}"