---
package_manager: apt
docker_repo_url: https://download.docker.com/linux/ubuntu
git_package: git
nginx_package: nginx
docker_package: docker-ce
docker_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common