---
- name: Install required Docker dependencies
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_dependencies }}"

- name: Add Docker GPG key (Debian-based)
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository (Debian)
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
    state: present

- name: Update apt cache (Debian-based)
  apt:
    update_cache: yes

- name: Install Docker
  package:
    name: "{{ docker_package }}"
    state: present

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Display the Ansible user
  debug:
    msg: "The Ansible user is {{ ansible_user }}"

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker