---
- name: Install Git
  package:
    name: "{{ git_package }}"
    state: present
  when: git_package is defined
- name: Set the banner
  template:
    src: ./files/banner-server2.txt
    dest: /etc/motd
  when: ansible_nodename== "home-server2"

- name: Include task to install Docker
  include_tasks: docker.yml

- name: Include task to install WireGuard
  include_tasks: wireguard.yml

- name: Include task to Install Nginx
  include_tasks: nginx.yml