---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install Git
  package:
    name: "{{ git_package }}"
    state: present
  when: git_package is defined

- name: Include task to install WireGuard
  include_tasks: wireguard.yml

- name: Include task to configure WireGuard
  include_tasks: nginx.yml

- name: Include task to start WireGuard
  include_tasks: docker.yml