---
- name: Install WireGuard (CentOS)
  yum:
    name: wireguard-tools
    state: present
  when: ansible_os_family == "RedHat"

- name: Clone WireGuard Docker Compose repository (Debian)
  git:
    repo: "{{ docker_github_url }}"
    dest: "{{ home_dir }}/server-docker"
    force: yes
  when: ansible_os_family == "Debian"

- name: Copy .env file to the WireGuard Docker Compose directory
  copy:
    src: files/.env
    dest: "{{ home_dir }}/server-docker/wireguard/.env"
  when: ansible_os_family == "Debian"

- name: Check if Docker network exists
  command: docker network ls --filter name=my_shared_network --format '{{ "{{" }} .Name {{ "}}" }}'
  register: existing_network

- name: Create Docker network if not exists
  command: docker network create my_shared_network
  when: existing_network.stdout != 'my_shared_network'

- name: Start WireGuard using Docker Compose (Debian)
  command: docker compose up -d
  args:
    chdir: "{{ home_dir }}/server-docker/wireguard"
  when: ansible_os_family == "Debian"