---
# Clone the GitHub repository with Docker Compose files
- name: Clone GitHub repository
  ansible.builtin.git:
    repo: "{{ docker_github_url }}"
    dest: "{{ home_dir }}/server-docker"
    force: yes
    version: main
  when: apps is defined

- name: Copy the environment file for each app
  ansible.builtin.copy:
    src: "files/{{ item }}.env"
    dest: "{{ home_dir }}/server-docker/{{ item }}/.env"
    mode: '0644'
  loop: "{{ apps }}"
  when: apps is defined

# Deploy the apps using Docker Compose
- name: Deploy application using Docker Compose
  ansible.builtin.shell: |
    docker-compose up -d
  args:
    chdir: "{{ home_dir }}/server-docker/{{ item }}"
  loop: "{{ apps }}"
  notify: Restart Docker Compose