name: Deploy Nginx Configuration via Ansible

on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  reload_nginx:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: ansible-playbook playbook/nginx.yml
  notify:
    runs-on: self-hosted
    needs: reload_nginx
    steps:
      - name: send telegram message on pushh
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            BUILD = ${{ needs.reload_nginx.result }}
            ${{ github.actor }} created commit: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
